# Generated by Django 2.2.5 on 2020-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mcin',
            field=models.CharField(default='1234567890', max_length=30),
        ),
    ]
